config/routes.rb
Rails.application.routes.draw do
  
  
  resources :enquiries
  resources :presences
  resources :answers
  resources :questions
  resources :channels
  # Added by Koudoku.
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end


  resources :messages
  resources :teams
  resources :users
  root to: 'marketing#index', constraints: { subdomain: '' }
  get '/', to: 'marketing#index', constraints: { subdomain: 'www' }
  get '/', to: 'users#index', constraints: { subdomain: /.+/ }

  get '/plans', to: 'marketing#plans'
  get '/privacy', to: 'marketing#privacy'
  get '/terms', to: 'marketing#terms'
  get '/working', to: 'marketing#working'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'




end

app/models/presence.rb
class Presence < ActiveRecord::Base

  def active_members
    User.where(:id=>active_ids)
  end

end

app/controllers/presences_controller.rb
class PresencesController < ApplicationController
  before_action :set_presence, only: [:show, :edit, :update, :destroy]

  # GET /presences
  # GET /presences.json
  def index
    @presences = current_team.presences
  end

  # GET /presences/1
  # GET /presences/1.json
  def show
  end

  # # GET /presences/new
  # def new
  #   @presence = Presence.new
  # end

  # # GET /presences/1/edit
  # def edit
  # end

  # # POST /presences
  # # POST /presences.json
  # def create
  #   @presence = Presence.new(presence_params)

  #   respond_to do |format|
  #     if @presence.save
  #       format.html { redirect_to @presence, notice: 'Presence was successfully created.' }
  #       format.json { render :show, status: :created, location: @presence }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @presence.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /presences/1
  # # PATCH/PUT /presences/1.json
  # def update
  #   respond_to do |format|
  #     if @presence.update(presence_params)
  #       format.html { redirect_to @presence, notice: 'Presence was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @presence }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @presence.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /presences/1
  # # DELETE /presences/1.json
  # def destroy
  #   @presence.destroy
  #   respond_to do |format|
  #     format.html { redirect_to presences_url, notice: 'Presence was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presence
      @presence = Presence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def presence_params
      params.require(:presence).permit(:team_id, :team_uid, :active_ids, :active_uids, :away_ids, :away_uids, :slack_api_data, :checked_at)
    end
end

app/helpers/presences_helper.rb
module PresencesHelper
end

app/views/presences/_form.html.haml
= simple_form_for(@presence) do |f|
  = f.error_notification

  .form-inputs
    = f.input :team_id
    = f.input :team_uid
    = f.input :active_ids
    = f.input :active_uids
    = f.input :away_ids
    = f.input :away_uids
    = f.input :slack_api_data
    = f.input :checked_at

  .form-actions
    = f.button :submit

app/views/presences/edit.html.haml
%h1 Editing presence

= render 'form'

= link_to 'Show', @presence
\|
= link_to 'Back', presences_path

app/views/presences/index.html.haml
.row
  .col-md-12
    %h1 Presence
.row
  - @presences.each do |presence|
    .col-md-6
      .panel.panel-default
        .panel-heading
          %h3.panel-title
            = presence.checked_at
            %small
              = "(#{presence.active_ids.count})"
        .panel-body
          %ul.avatar-list
            - presence.active_members.limit(32).each do |member|
              %li.avatar-list-item
                = link_to member do
                  = image_tag member.image_url, :class=>"img-circle"

app/views/presences/new.html.haml
%h1 New presence

= render 'form'

= link_to 'Back', presences_path

app/views/presences/show.html.haml
%p#notice= notice

%p
  %b Team:
  = @presence.team_id
%p
  %b Team uid:
  = @presence.team_uid
%p
  %b Active ids:
  = @presence.active_ids
%p
  %b Active uids:
  = @presence.active_uids
%p
  %b Away ids:
  = @presence.away_ids
%p
  %b Away uids:
  = @presence.away_uids
%p
  %b Slack api data:
  = @presence.slack_api_data
%p
  %b Checked at:
  = @presence.checked_at

= link_to 'Edit', edit_presence_path(@presence)
\|
= link_to 'Back', presences_path