config/routes.rb
Rails.application.routes.draw do
  
  
  resources :enquiries
  resources :presences
  resources :answers
  resources :questions
  resources :channels
  # Added by Koudoku.
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end


  resources :messages
  resources :teams
  resources :users
  root to: 'marketing#index', constraints: { subdomain: '' }
  get '/', to: 'marketing#index', constraints: { subdomain: 'www' }
  get '/', to: 'users#index', constraints: { subdomain: /.+/ }

  get '/plans', to: 'marketing#plans'
  get '/privacy', to: 'marketing#privacy'
  get '/terms', to: 'marketing#terms'
  get '/working', to: 'marketing#working'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'




end

app/models/message.rb
class Message < ActiveRecord::Base

  belongs_to :team, foreign_key: :team_uid, primary_key: :uid
  belongs_to :channel, foreign_key: :channel_uid, primary_key: :uid
  belongs_to :user, foreign_key: :user_uid, primary_key: :uid
  has_one :answer, foreign_key: :answer_message_id

  def self.create_from_slack_data(data, team)
    logger.info "CREATING MESSAGE"
    m = Message.where(ts: data["ts"], channel_uid: data["channel"], team_id: team.id, team_uid: team.uid).first_or_create do |message|
      message.timestamp = Time.at(data["ts"].split(".")[0].to_i)
      message.slack_data = data
      data_message = data["message"]
      data_message ||= data
      message.message_type = data_message["type"]
      message.message_subtype = data_message["subtype"]
      message.user_uid = data_message["user"]
      message.text = data_message["text"]
    end
    return m
  end

  def reply(text)
    puts "Sending to #{channel_uid}: #{text}"
    team.send_message(channel_uid,text)
  end

  def answer_question
    puts "ANSWERING QUESTION"
    user.answer_question(self)
  end

  def is_positive?
    ['continue', 'y', 'yes', 'yea', 'yeah', 'yep', 'OK', 'ok',  'affirmative', 'aye', 'roger', 'yup', 'yuppers', 'ja', 'surely', 'amen', 'totally', 'yessir'].include?(self.text)
  end

  def is_negative?
    ['n', 'no', 'nope', 'nay'].include?(self.text)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = current_team.messages
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # # GET /messages/new
  # def new
  #   @message = Message.new
  # end

  # # GET /messages/1/edit
  # def edit
  # end

  # # POST /messages
  # # POST /messages.json
  # def create
  #   @message = Message.new(message_params)

  #   respond_to do |format|
  #     if @message.save
  #       format.html { redirect_to @message, notice: 'Message was successfully created.' }
  #       format.json { render :show, status: :created, location: @message }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @message.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /messages/1
  # # PATCH/PUT /messages/1.json
  # def update
  #   respond_to do |format|
  #     if @message.update(message_params)
  #       format.html { redirect_to @message, notice: 'Message was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @message }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @message.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /messages/1
  # # DELETE /messages/1.json
  # def destroy
  #   @message.destroy
  #   respond_to do |format|
  #     format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:channel_uid, :channel_id, :team_uid, :team_id, :text, :ts, :timestamp, :message_type, :message_subtype, :user_uid, :user_id, :properties, :slack_data)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= simple_form_for(@message) do |f|
  = f.error_notification

  .form-inputs
    = f.input :channel_uid
    = f.input :channel_id
    = f.input :team_uid
    = f.input :team_id
    = f.input :text
    = f.input :ts
    = f.input :timestamp
    = f.input :message_type
    = f.input :message_subtype
    = f.input :user_uid
    = f.input :user_id
    = f.input :properties
    = f.input :slack_data

  .form-actions
    = f.button :submit

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
.container.m-y-md
  .col-md-12
    %ul.list-group.media-list.media-list-stream
      - @messages.each do |message|
        %li.media.list-group-item.p-a
          =link_to message.user, :class=>"media-left" do
            = image_tag message.user.image_url, :class=>"media-object img-circle"
          .media-body
            .media-body-text
              .media-heading
                %small.pull-right.text-muted
                  =message.channel_uid
                %small.pull-right.text-muted
                  =message.timestamp

                %h5
                  = message.user.name
              %p
                = Slack::Messages::Formatting.unescape(message.text)

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/show.html.haml
%p#notice= notice

%p
  %b Channel uid:
  = @message.channel_uid
%p
  %b Channel:
  = @message.channel_id
%p
  %b Team uid:
  = @message.team_uid
%p
  %b Team:
  = @message.team_id
%p
  %b Text:
  = @message.text
%p
  %b Ts:
  = @message.ts
%p
  %b Timestamp:
  = @message.timestamp
%p
  %b Message type:
  = @message.message_type
%p
  %b Message subtype:
  = @message.message_subtype
%p
  %b User uid:
  = @message.user_uid
%p
  %b User:
  = @message.user_id
%p
  %b Properties:
  = @message.properties
%p
  %b Slack data:
  = @message.slack_data

= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path