config/routes.rb
Rails.application.routes.draw do
  
  
  resources :enquiries
  resources :presences
  resources :answers
  resources :questions
  resources :channels
  # Added by Koudoku.
  mount Koudoku::Engine, at: 'koudoku'
  scope module: 'koudoku' do
    get 'pricing' => 'subscriptions#index', as: 'pricing'
  end


  resources :messages
  resources :teams
  resources :users
  root to: 'marketing#index', constraints: { subdomain: '' }
  get '/', to: 'marketing#index', constraints: { subdomain: 'www' }
  get '/', to: 'users#index', constraints: { subdomain: /.+/ }

  get '/plans', to: 'marketing#plans'
  get '/privacy', to: 'marketing#privacy'
  get '/terms', to: 'marketing#terms'
  get '/working', to: 'marketing#working'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'




end

app/models/answer.rb
class Answer < ActiveRecord::Base

  include Twitter::Autolink

  after_save :ask_question

  belongs_to :user
  belongs_to :question

  #property_name

  def self.check_for_url_or_twitter
    Answer.all.each do |a|
      a.check_for_url_or_twitter
    end
  end

  def background_image

  end

  def color

  end

  def image_url

  end

  def check_for_url_or_twitter
    t = unescaped_answer
    unless t.nil?
      u = URI::extract(auto_link(t)).first
      unless u.blank?
        self.url = u
        self.save
      end
    end
  end


  def unescaped_answer
    unless answer_text.nil?
      CGI.unescapeHTML(answer_text.gsub(/[“”]/, '"')
        .gsub(/[‘’]/, "'")
        .gsub(/<(?<sign>[?@#!]?)(?<dt>.*?)>/) do |match|
          sign = $~[:sign]
          dt = $~[:dt]
          rhs = dt.split('|', 2).first
          case sign
          when '@', '!'
            "@#{User.find_by_uid(rhs).name}"
          when '#'
            "##{rhs}"
          else
            rhs
          end
        end)
    end
  end


  def self.ask_stand_alone_question(user, text, property_name)
    a = Answer.create(:user_id=>user.id, :question_text=>text, :property_name=>property_name)
    # m = user.send_im(text)
    # a.question_message_id = m.id
    # a.question_text = m.text
    # a.asked_at = Time.now
    # a.save
  end

  def ask_question
    sleep(2)
    if question_message_id.nil?
      if self.question_text.nil?
        m = user.send_im(question.text)
      else
        m = user.send_im(self.question_text)
      end
      self.question_message_id = m.id
      self.question_text = m.text
      self.asked_at = Time.now
      self.save
    end
  end

  def receive_answer(message)
    if answer_message_id.nil?
      self.answer_message_id = message.id
      self.answer_text = message.text
      self.answered_at = Time.now
      self.save
      m = user.send_im(question.response) unless question.nil? || question.response.nil?
    end
  end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = Answer.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # # GET /answers/new
  # def new
  #   @answer = Answer.new
  # end

  # # GET /answers/1/edit
  # def edit
  # end

  # # POST /answers
  # # POST /answers.json
  # def create
  #   @answer = Answer.new(answer_params)

  #   respond_to do |format|
  #     if @answer.save
  #       format.html { redirect_to @answer.user, notice: 'Question was successfully asked.' }
  #       format.json { render :show, status: :created, location: @answer }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @answer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /answers/1
  # # PATCH/PUT /answers/1.json
  # def update
  #   respond_to do |format|
  #     if @answer.update(answer_params)
  #       format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @answer }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @answer.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /answers/1
  # # DELETE /answers/1.json
  # def destroy
  #   @answer.destroy
  #   respond_to do |format|
  #     format.html { redirect_to answers_url, notice: 'Answer was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:user_id, :question_id, :question_message_id, :question_text, :answer_message_id, :answer_text, :url, :properties, :asked_at, :answered_at, :asked_by)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.haml
.panel.panel-default
  .panel-heading{:style => "background-image: url(#{answer.background_image}); background-color: ##{answer.color}"}
    .panel-title
      =link_to answer, :class=>"text-inherit" do
        =answer.question_text
  .panel-body.text-center
    %p.m-b-md{:style=>"font-size:2em;"}
      -if user_signed_in? && current_user.team_uid == current_team.uid
        - if answer.url.present?
          = link_to answer.url, answer.url, :class=>"embedly-card"
        = raw auto_link(answer.unescaped_answer)
      -else
        = link_to "Sign in to #{current_team.name} to view", main_app.signin_url(:subdomain=>"", :team=>current_team.uid, :scope=>"identify")


    / %ul.panel-menu
    /   %li.panel-menu-item
    /     %a.text-inherit
    /       = user.answered_questions.count
    /       questions answerd
    /   %li.panel-menu-item
    /     %a.text-inherit
    /       = user.channels.count
    /       channels joined
    /   %li.panel-menu-item
    /     %a.text-inherit
    /       =user.presences.count
    /       days present
          
    / %a.btn.btn-success{:href => "#"}
    /   Contact
    /   = user.name
    / = link_to "Learn more", user, :class=>"btn btn-primary"

app/views/answers/_form.html.haml
= simple_form_for(@answer) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :question_id
    = f.input :question_message_id
    = f.input :question_text
    = f.input :answer_message_id
    = f.input :answer_text
    = f.input :url
    = f.input :asked_at
    = f.input :answered_at
    = f.input :asked_by

  .form-actions
    = f.button :submit

app/views/answers/edit.html.haml
%h1 Editing answer

= render 'form'

= link_to 'Show', @answer
\|
= link_to 'Back', answers_path

app/views/answers/index.html.haml
%h1 Listing answers

%table
  %thead
    %tr
      %th User
      %th Question
      %th Question message
      %th Question text
      %th Answer message
      %th Answer text
      %th Url
      %th Properties
      %th Asked at
      %th Answered at
      %th Asked by
      %th
      %th
      %th

  %tbody
    - @answers.each do |answer|
      %tr
        %td= answer.user_id
        %td= answer.question_id
        %td= answer.question_message_id
        %td= answer.question_text
        %td= answer.answer_message_id
        %td= answer.answer_text
        %td= answer.url
        %td= answer.properties
        %td= answer.asked_at
        %td= answer.answered_at
        %td= answer.asked_by
        %td= link_to 'Show', answer
        %td= link_to 'Edit', edit_answer_path(answer)
        %td= link_to 'Destroy', answer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Answer', new_answer_path

app/views/answers/new.html.haml
%h1 New answer

= render 'form'

= link_to 'Back', answers_path

app/views/answers/show.html.haml
%p#notice= notice

%p
  %b User:
  = @answer.user_id
%p
  %b Question:
  = @answer.question_id
%p
  %b Question message:
  = @answer.question_message_id
%p
  %b Question text:
  = @answer.question_text
%p
  %b Answer message:
  = @answer.answer_message_id
%p
  %b Answer text:
  = @answer.answer_text
%p
  %b Url:
  = @answer.url
%p
  %b Properties:
  = @answer.properties
%p
  %b Asked at:
  = @answer.asked_at
%p
  %b Answered at:
  = @answer.answered_at
%p
  %b Asked by:
  = @answer.asked_by

= link_to 'Edit', edit_answer_path(@answer)
\|
= link_to 'Back', answers_path